#!/bin/bash

set -e

SRC_FILE="$1"
DST_PATH="$2"

info() {
     local green="\033[1;32m"
     local normal="\033[0m"
     echo -e "[${green}INFO${normal}] $1"
}

error() {
     local red="\033[1;31m"
     local normal="\033[0m"
     echo -e "[${red}ERROR${normal}] $1"
}

usage() {
cat << EOF
USAGE:
    $0 srcfile dstpath

EXAMPLE:
    $0 img.png ~/icons

DESCRIPTION:
    This script generates ios app icons.

    srcfile - The source png image.
    dstpath - The destination path where the icons will be saved.

    This script is depend on ImageMagick. So you must install ImageMagick first
    You can use 'brew install imagemagick' to install it

AUTHOR:
    giulio.marin@me.com>
EOF
}

###########
# Main
###########

# Check imagemagick
command -v convert >/dev/null 2>&1 || { error >&2 "ImageMagick is not installed. Please install it first."; exit -1; }

# Check param
if [ $# != 2 ];then
    usage
    exit -1
fi

# Check whether dst path exist.
mkdir -p "$DST_PATH"

# Generate, refer to: https://developer.apple.com/library/ios/qa/qa1686/_index.html
info 'Generate iTunesArtwork.png'
convert "$SRC_FILE" -resize 512x512 "$DST_PATH/iTunesArtwork.png"
info 'Generate iTunesArtwork@2x.png'
convert "$SRC_FILE" -resize 1024x1024 "$DST_PATH/iTunesArtwork@2x.png"

# iPhone, iPad Pro, iPad, iPad mini notification
info 'Generate Icon-20.png'
convert "$SRC_FILE" -resize 20x20 "$DST_PATH/Icon-20.png"
info 'Generate Icon-20@2x.png'
convert "$SRC_FILE" -resize 40x40 "$DST_PATH/Icon-20@2x.png"
info 'Generate Icon-40@2x.png'
convert "$SRC_FILE" -resize 60x60 "$DST_PATH/Icon-20@3x.png"

# iPhone, iPad Pro, iPad, iPad mini settings
info 'Generate Icon-29.png'
convert "$SRC_FILE" -resize 29x29 "$DST_PATH/Icon-29.png"
info 'Generate Icon-29@2x.png'
convert "$SRC_FILE" -resize 58x58 "$DST_PATH/Icon-29@2x.png"
info 'Generate Icon-29@3x.png'
convert "$SRC_FILE" -resize 87x87 "$DST_PATH/Icon-29@3x.png"

# iPhone, iPad Pro, iPad, iPad mini spotlight
info 'Generate Icon-40.png'
convert "$SRC_FILE" -resize 40x40 "$DST_PATH/Icon-40.png"
info 'Generate Icon-40@2x.png'
convert "$SRC_FILE" -resize 80x80 "$DST_PATH/Icon-40@2x.png"
info 'Generate Icon-40@3x.png'
convert "$SRC_FILE" -resize 120x120 "$DST_PATH/Icon-40@3x.png"

# iPhone
info 'Generate Icon-60.png'
convert "$SRC_FILE" -resize 60x60 "$DST_PATH/Icon-60.png"
info 'Generate Icon-60@2x.png'
convert "$SRC_FILE" -resize 120x120 "$DST_PATH/Icon-60@2x.png"
info 'Generate Icon-60@3x.png'
convert "$SRC_FILE" -resize 180x180 "$DST_PATH/Icon-60@3x.png"

# iPad, iPad mini
info 'Generate Icon-76.png'
convert "$SRC_FILE" -resize 76x76 "$DST_PATH/Icon-76.png"
info 'Generate Icon-76@2x.png'
convert "$SRC_FILE" -resize 152x152 "$DST_PATH/Icon-76@2x.png"

info 'Generate Icon-57.png'
convert "$SRC_FILE" -resize 57x57 "$DST_PATH/Icon-57.png"
info 'Generate Icon-57@2x.png'
convert "$SRC_FILE" -resize 114x114 "$DST_PATH/Icon-57@2x.png"

# iPad Pro
info 'Generate Icon-83.5@2x.png'
convert "$SRC_FILE" -resize 167x167 "$DST_PATH/Icon-83.5@2x.png"

info 'Generate Icon-72.png'
convert "$SRC_FILE" -resize 72x72 "$DST_PATH/Icon-72.png"
info 'Generate Icon-72@2x.png'
convert "$SRC_FILE" -resize 144x144 "$DST_PATH/Icon-72@2x.png"

info 'Generate Icon-50.png'
convert "$SRC_FILE" -resize 50x50 "$DST_PATH/Icon-50.png"
info 'Generate Icon-50@2x.png'
convert "$SRC_FILE" -resize 100x100 "$DST_PATH/Icon-50@2x.png"

info 'Generate Done.'
